### ISSUE TITLE
hidden SSID

### ISSUE THREAD

**Issue by zajaklis** [Edzelf/ESP32-Radio#1]
radio does not connects to hidden SSID and then starts too run its own AP

**Comment by Edzelf** [comment]
Yes, it is designed that way.  I will see if I can fix it.

**Comment by zajaklis** [comment]
just tested with with built in arduino ide WiFiMulti example. did not connected to hidden ssid, so problem is not related to ESP32-Radio.

**Comment by Edzelf** [comment]
What I can do is connect to WiFi directly if only one (wifi_00) is defined in de preferences.

**Comment by zajaklis** [comment]
that would be great, thank you

**Comment by Edzelf** [comment]
Should be fixed now.

**Comment by zajaklis** [comment]
tested, works with hidden ssid now, thanks
