### ISSUE TITLE
Button connection

### ISSUE THREAD

**Issue by lonelyjack** [Edzelf/ESP32-Radio#10]
![img-20170605-wa0000](https://cloud.githubusercontent.com/assets/28937662/26764599/036c05e4-4983-11e7-983e-adee4dfbc763.jpg)
is it right?

**Comment by Edzelf** [comment]
There is no pull-up required for GPIO12.  At least not on a standard Dev Board.  A switch to GND is sufficient.  A pull-up does not harm either.

**Comment by lonelyjack** [comment]
Out of the resistor, the diagram is right?

**Comment by Edzelf** [comment]
Yes, try it and look at the debug logging at the serial output.

**Comment by lonelyjack** [comment]
What about other GPIOs? 13,14,17,22,25,26,27,32,33? Is there no pull-up required?

**Comment by Edzelf** [comment]
Try it, or read the documentation.

**Comment by lonelyjack** [comment]
There's an empty fields in your overview for these pins

**Comment by lonelyjack** [comment]
Well, it's rebooting without pull-ups

**Comment by Edzelf** [comment]
Now, take a wire and ground pins 13, 14,17,.... one by one.  Watch the logging.

**Comment by Edzelf** [comment]
If you mean "it keeps rebooting", then you have a weak power supply.  Add a big capacitor like 3300 microFarad between 5 Volt and ground.
