### ISSUE TITLE
can´t compile

### ISSUE THREAD

**Issue by Feuer001** [Edzelf/ESP32-Radio#122]
I have downloaded esp32-radio and when I try to compile the software I get an error message: no matching function for call to 'Adafruit_ST7735 :: Adafruit_ST7735 (int8_t &, int8_t &)'
What can I do?

**Comment by Edzelf** [comment]
Do you have the latest version of the adafruit st7735 library?

**Comment by Feuer001** [comment]
No, I had a modified one.
Now everything is fine.
Thank you!!
