### ISSUE TITLE
VS1053 ok on old but not the latest ESP32_radio version

### ISSUE THREAD

**Issue by uwe-pt** [Edzelf/ESP32-Radio#131]
Hi, on the older version of ESP32_radio (June 2017) my VS1053 runs without any problem, but on the latest version I get the 'd: vs1053 not properly installed!' error. I checked all wiring thoroughly, for solder bridges at the chip pins and reinstalled both software versions several times. Any idea how to solve this? Thanks, Uwe

**Comment by Edzelf** [comment]
Looks like an SPI problem.  Check the wiring and the debug output concerning the SPI.  Remember that all the pin definitions must be present in the configuration.  You may edit these in the config page of the webinterface.
