### ISSUE TITLE
sd_cs value missing

### ISSUE THREAD

**Issue by uwe-pt** [Edzelf/ESP32-Radio#136]
With the original files SD does not work. Adjusting sd_cs in web config or loading default results in no improvement, but when I fix the pin number in:
   { "pin_sd_cs",    &ini_block.sd_cs_pin,       21          },
everything works as expected.

**Comment by Edzelf** [comment]
The normal way to specify the CS pin is adding the line:
`pin_sd_cs = 21`
in the config page of the webinterface.

**Comment by uwe-pt** [comment]
Changed to pin_sd_cs in defaultprefs.h. Now everything ok. Thank you!

**Comment by Edzelf** [comment]
Defaultprefs.h just gives an example.  But I will correct the typo.
