### ISSUE TITLE
Negative clk_offset Doesn't Work

### ISSUE THREAD

**Issue by mikey60** [Edzelf/ESP32-Radio#159]
A negative clk_offset (timezone) is not handled correctly. The negative clk_offset actually gets changed to a positive value by statement 4821 of Esp32_radio.ino.  I just added a variable to preserve the original value and used that value in statement 5035.  There are probably ways to correct the issue.

**Comment by Edzelf** [comment]
You are right.  Fixed.

**Comment by mikey60** [comment]
Negative time zone works fine in the latest version (06-aug-2018)
