### ISSUE TITLE
Compile issue(s) (Windows)

### ISSUE THREAD

**Issue by acolwill** [Edzelf/ESP32-Radio#160]
I've got a working Arduino platform working under Win10 however having issues getting the main Esp32_radio.ino to compile...

I'm using the newly created Espressif board repo [https://dl.espressif.com/dl/package_esp32_index.json] and have successfully compiled other sketches for esp32 boards however none using WiFiMulti previously.

I'm getting compile errors for wifi_auth_mode_t:

`Esp32_radio:1617: error: 'wifi_auth_mode_t' was not declared in this scope

 const char* getEncryptionType ( wifi_auth_mode_t thisType )`

Additionally, even though I've got display declarations commented out it still tries to load the headers and complains!

`//#define BLUETFT                        // Works also for RED TFT 128x160`
`#define OLED                         // 64x128 I2C OLED`
`//#define DUMMYTFT                     // Dummy display`
`//#define LCD1602I2C                   // LCD 1602 display with I2C backpack`
`//#define ILI9341  `

`Dummytft.h:36: error: 'scrseg_struct' does not name a type`
 `scrseg_struct     tftdata[TFTSECS] =                        // Screen divided in 3 segments + 1 overlay`
 `^`
`In file included from C:\Users\Avatar\Documents\Arduino\sketches\esp32_Radio\Esp32_radio.ino:427:0:`

`SSD1306.h:48: error: conflicting declaration 'SSD1306* tft'`
` SSD1306* tft = NULL ;`
 `         ^`

`C:\Users\Avatar\Documents\Arduino\sketches\esp32_Radio\Dummytft.h:33:7: note: previous declaration as 'void* tft'`
` void* tft = NULL ;`
`       ^`

`In file included from C:\Users\Avatar\Documents\Arduino\sketches\esp32_Radio\Esp32_radio.ino:427:0:`
`sketch\SSD1306.h: In function 'bool dsp_begin()':`
`SSD1306.h:74: error: redefinition of 'bool dsp_begin()'`
 `bool dsp_begin()`

`      ^`

`C:\Users\Avatar\Documents\Arduino\sketches\esp32_Radio\Dummytft.h:28:6: note: 'bool dsp_begin()' previously defined here`
` bool dsp_begin()`
`      ^`
(amongst other compile errors)`
Any ideas?

**Comment by Edzelf** [comment]
You need to define ONE of the displays.  Use DUMMYTFT if there is no display, although it's better to leave the source code as it is.
wifi_auth_mode_t is defined in esp_wifi_types.h.
That file should be in ..../AppData/Local/Arduino15/packages/esp32/hardware/esp32/1.0.0/tools/sdk/include/esp32/esp_wifi_types.h

**Comment by acolwill** [comment]
Only OLED is uncommented. All other display types are excluded.

I can confirm file esp_wifi_types.h being present ...\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\tools\sdk\include\esp32
I'll have to check later as to why it's not picking it up

**Comment by acolwill** [comment]
Doesn't make any sense.
I've double checked, the ESP32 SDK is being seen correctly.
Downloaded your source again and made the same changes as previous and it's worked...
I have a feeling there was ID-10T error.
