### ISSUE TITLE
SLOW SPI

### ISSUE THREAD

**Issue by paysan18** [Edzelf/ESP32-Radio#190]
I'm building this very promissing Internet radio.
The ESP32 is a ESP32-DEVKITV1 with 30 pins.
And I use the VS1053B.

During the startup I  got the message SLOW SPI and VS1053 not properly installed.
I double checked the wiring and all looks ok.

Who has an idea how to fix this.
[debug.txt](https://github.com/Edzelf/ESP32-Radio/files/2616682/debug.txt)

![screenshot from 2018-11-26 17-09-43](https://user-images.githubusercontent.com/11871478/49031135-70db7e00-f1a9-11e8-8ba7-461a661a94f5.png)

**Comment by Edzelf** [comment]
There is no setting for pin_vs_cs, pin_vs_dcs and pin_vs_dreq.  Did you run the Esp-radio-int sketch?

**Comment by Edzelf** [comment]
Start the webinterface and enter the proper settings for the VS1053 pins.

**Comment by paysan18** [comment]
I did, see my next issue #191. 
Sofar no luck....

**Comment by paysan18** [comment]
This issue can be closed. It was 1 typo in the Esp-radio-int sketch.
