### ISSUE TITLE
How to change the station with rotary switch?

### ISSUE THREAD

**Issue by mrohner** [Edzelf/ESP32-Radio#194]
When pressing the rotary switch twice I can change the preset channel but the music does not change

D: Double click
D: Encoder mode set to PRESET
D: Rotation count -1
D: Preset is 3
D: Rotation count -1
D: Preset is 2
D: Rotation count -1
D: Preset is 1
D: Encoder mode back to VOLUME

still channel 3 is playing. How do I do change the channel with the rotary switch?

**Comment by Edzelf** [comment]
End the command with a single click:
Double click, turn, singel click.

**Comment by mrohner** [comment]
Thanks
