### ISSUE TITLE
Installmof Nextion display

### ISSUE THREAD

**Issue by paysan18** [Edzelf/ESP32-Radio#197]
Hello all, I want to connect a Nextion display to the radio.
When I supply power to the display it starts running a kind of Demo.
So it seems I have to install new firmware into it.
I found inside the folder NEXTION 2 files. A .HMI of about 35kB and a .tft file of 2 bytes.
After copying the .HMI file to a fresh formatted SD card I inserted this card into the display and connnected the power. On the screen comes: SD update...... and all remains like this.
What do I do wrong?
Regards, Wim

**Comment by Edzelf** [comment]
Looks like the .tft file is damaged.  You need a .tft file to upload the data to the nextion.  You may use the nextion compiler to create the .tft file.  I will upload a new .tft file tomorrow.

**Comment by paysan18** [comment]
Ok, but what to do with the .HMI file?

**Comment by Edzelf** [comment]
.hmi is the source file.  It is the input for the Nextion compiler.  You may edit the .hmi file to adapt the  nextion interface to your needs.

**Comment by Edzelf** [comment]
.tft file is now complete (139 kB).

**Comment by paysan18** [comment]
Great, thank a lot. I will try it this afternoon.

**Comment by paysan18** [comment]
Ik probeer het van,iddag. Moet nu even weg.

Groeten, Wim

**Comment by paysan18** [comment]
Update succeeded. But during te restart of the radio the display shows:

Read SD card
27 tracks on SD

and this loops every second.

There is no card inserted.

**Comment by paysan18** [comment]
Everything is OK now. It seemed I also had problems with the powersupply.
Ed, thanks for uploading the .tft file.

**Comment by paysan18** [comment]
Issue can be closed.
