### ISSUE TITLE
No sound ....

### ISSUE THREAD

**Issue by cherob67** [Edzelf/ESP32-Radio#204]
Hello
I an trying to make the ESP32-RADIO. I succeed in wifi connection and radio server connection. I also succeed in sdcard connection. But i have error in fast SPI testing VS1053.
I use a ESP-Wroom-32 and VS1053 bought on internet like this one ([https://www.amazon.fr/VS1053B-Arduino-Breakout-Real-Time-Recording/dp/B07J63G1RX/ref=sr_1_52?ie=UTF8&qid=1545249974&sr=8-52&keywords=vs1053](https://www.amazon.fr/VS1053B-Arduino-Breakout-Real-Time-Recording/dp/B07J63G1RX/ref=sr_1_52?ie=UTF8&qid=1545249974&sr=8-52&keywords=vs1053)).
The wiring has verified at many time and now I need some help to find a solution.
Thanks

I join the serial response at starting:
D: Starting ESP32-radio running on CPU 1 at 240 MHz.  Version Thu, 04 Oct 2018 07:22:32 GMT.  Free memory 233728
D: Display type is OLED
D: Partition nvs found, 20480 bytes
D: Read 29 keys from NVS
D: pin_ir set to -1
D: pin_enc_clk set to -1
D: pin_enc_dt set to -1
D: pin_enc_sw set to -1
D: pin_tft_cs set to -1
D: pin_tft_dc set to -1
D: pin_tft_scl set to -1
D: pin_tft_sda set to -1
D: pin_tft_bl set to -1
D: pin_tft_blx set to -1
D: pin_sd_cs set to 22
D: pin_vs_cs set to 5
D: pin_vs_dcs set to 32
D: pin_vs_dreq set to 4
D: pin_shutdown set to -1
D: pin_shutdownx set to -1
D: pin_spi_sck set to 18
D: pin_spi_miso set to 19
D: pin_spi_mosi set to 23
D: GPIO0 is HIGH
D: GPIO2 is LOW, probably no PULL-UP
D: GPIO4 is HIGH
D: GPIO5 is HIGH
D: GPIO12 is HIGH
D: GPIO13 is HIGH
D: GPIO14 is HIGH
D: GPIO15 is HIGH
D: GPIO16 is HIGH
D: GPIO17 is HIGH
D: GPIO18 is HIGH
D: GPIO19 is HIGH
D: GPIO21 is HIGH
D: GPIO22 is HIGH
D: GPIO23 is HIGH
D: GPIO25 is HIGH
D: GPIO26 is HIGH
D: GPIO27 is HIGH
D: GPIO32 is HIGH
D: GPIO33 is HIGH
D: GPIO34 is LOW, probably no PULL-UP
D: GPIO35 is LOW, probably no PULL-UP
D: GPIO39 is LOW, probably no PULL-UP
D: gpio_00 will execute uppreset = 1
D: gpio_12 will execute upvolume = 2
D: gpio_13 will execute downvolume = 2
D: Locate mp3 files on SD, may take a while...
D: 11 tracks on SD
D: Create list with acceptable WiFi networks
D: Added domicile_rc to list of networks
D: End adding networks
D: Scan Networks
D: Scan completed
D: Number of available networks: 5
D:  1 - Bbox-B476B850             Signal: -79 dBm, Encryption WPA_WPA2_PSK, 
D:  2 - domicile_rc               Signal: -84 dBm, Encryption WPA_WPA2_PSK, Acceptable
D:  3 - XXXX-1698                 Signal: -85 dBm, Encryption WPA_WPA2_PSK, 
D:  4 - rodgers25                 Signal: -89 dBm, Encryption WPA_WPA2_PSK, 
D:  5 - freebox_CeliaSXB          Signal: -91 dBm, Encryption WPA_PSK, 
D: End of list
D: Command: clk_dst with parameter 1
D: Command: clk_offset with parameter 1
D: Command: clk_server with parameter europe.pool.ntp.org
D: Command: gpio_00 with parameter uppreset = 1
D: Command: gpio_12 with parameter upvolume = 2
D: Command: gpio_13 with parameter downvolume = 2
D: Command: mqttbroker with parameter broker.hivemq.com
D: Command: mqttpasswd with parameter *******
D: Command: mqttport with parameter 1883
D: Command: mqttpubtopic with parameter P_espradioIP
D: Command: mqtttopic with parameter P_espradio
D: Command: mqtttpreset with parameter none
D: Command: mqttuser with parameter none
D: Command: preset with parameter 0
D: Command: preset_00 with parameter chai5she.cdn.dvmr.fr:80/franceinter-midfi.mp3
D: Command: preset_01 with parameter chai5she.cdn.dvmr.fr:80/francemusique-midfi.mp3
D: Command: preset_02 with parameter chai5she.cdn.dvmr.fr:80/franceculture-midfi.mp3
D: Command: preset_03 with parameter rfm-live-mp3-128.scdn.arkena.com/rfm.mp3
D: Command: preset_04 with parameter str0.creacast.com/frequence_verte_2
D: Command: preset_05 with parameter str0.creacast.com/rec
D: Command: preset_06 with parameter direct.radiopresence.com/radio-presence-lot
D: Command: preset_07 with parameter mp3lg4.tdf-cdn.com/9240/lag_180945.mp3
D: Command: preset_08 with parameter streaming.radio.rtl.fr/rtl-1-48-192*/
D: Command: toneha with parameter 13
D: Command: tonehf with parameter 15
D: Command: tonela with parameter 5
D: Command: tonelf with parameter 15
D: Command: volume with parameter 90
D: Slow SPI, Testing VS1053 read/write registers...
D: Fast SPI, Testing VS1053 read/write registers again...
D: VS1053 error retry SB:0399 R1:0399 R2:FFF8
D: VS1053 error retry SB:039C R1:0000 R2:0000
D: VS1053 error retry SB:039F R1:0000 R2:0000
D: VS1053 error retry SB:03A2 R1:0000 R2:0000
D: VS1053 error retry SB:03A5 R1:0000 R2:0000
D: VS1053 error retry SB:03A8 R1:0000 R2:0000
D: VS1053 error retry SB:03AB R1:0000 R2:0000
D: VS1053 error retry SB:03AE R1:0000 R2:0000
D: VS1053 error retry SB:03B1 R1:0000 R2:0000
D: VS1053 error retry SB:03B4 R1:0000 R2:0000
D: VS1053 error retry SB:03B7 R1:0000 R2:0000
D: VS1053 error retry SB:03BA R1:0000 R2:0000
D: VS1053 error retry SB:03BD R1:0000 R2:0000
D: VS1053 error retry SB:03C0 R1:0000 R2:0000
D: VS1053 error retry SB:03C3 R1:0000 R2:0000
D: VS1053 error retry SB:03C6 R1:0000 R2:0000
D: VS1053 error retry SB:03C9 R1:0000 R2:0000
D: VS1053 error retry SB:03CC R1:0000 R2:0000
D: VS1053 error retry SB:03CF R1:0000 R2:0000
D: VS1053 error retry SB:03D2 R1:0000 R2:0000
D: endFillByte is 0
D: Connect to WiFi
D: Try WiFi domicile_rc
D: Connected to domicile_rc
D: IP = 192.168.1.11
D: Start server for commands
D: Network found. Starting mqtt and OTA
D: MQTT uses prefix P25A4AE30
D: Init MQTT
D: MDNS responder started
D: Rotary encoder is disabled (-1/-1/-1)
D: STOP requested
D: New preset/file requested (0/0) from chai5she.cdn.dvmr.fr:80/franceinter-midfi.mp3
D: Connect to new host chai5she.cdn.dvmr.fr:80/franceinter-midfi.mp3
D: Connect to chai5she.cdn.dvmr.fr on port 80, extension /franceinter-midfi.mp3
D: (Re)connecting number 1 to MQTT broker.hivemq.com
D: Connected to server
D: Duration mp3loop 1
D: Switch to HEADER
D: Headerline: Server: nginx/1.6.2
D: Headerline: Content-Type: audio/mpeg
D: audio/mpeg seen.
D: Headerline: Transfer-Encoding: chunked
D: Headerline: Connection: close
D: Headerline: icy-metadata: 1
D: Headerline: icy-pub: 1
D: Headerline: Cache-Control: no-cache, no-store
D: Headerline: Access-Control-Allow-Origin: *
D: Headerline: Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type
D: l-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type seen.
D: Headerline: Access-Control-Allow-Methods: GET, OPTIONS, HEAD
D: Headerline: Expires: Mon, 26 Jul 1997 05:00:00 GMT
D: Switch to DATA, bitrate is 0, metaint is 0
D: Duration mp3loop 50
D: Duration mp3loop 191
D: Publish to topic P25A4AE30/ip : 192.168.1.11
D: Publish to topic P25A4AE30/preset : 0
D: Publish to topic P25A4AE30/playing : 1
D: Command client available
D: handlehttp started
D: Filename is: index.html
D: Start file reply for index.html
D: FileRequest received index.html
D: Length of page is 8088
D: Response send
D: Command client available
D: handlehttp started
D: Filename is: radio.css
D: Start file reply for radio.css
D: FileRequest received radio.css
D: Length of page is 2032
D: Response send
D: Command client available
D: handlehttp started
D: Get command is: settings
D: Send reply for settings
D: Publish to topic P25A4AE30/volume : 90
D: Command client available
D: handlehttp started
D: Filename is: about.html
D: Start file reply for about.html
D: FileRequest received about.html
D: Length of page is 1240
D: Response send
D: Command client available
D: handlehttp started
D: Get command is: getnetworks
D: Send reply for getnetworks
D: Command: getnetworks with parameter 0
D: Command client available
D: handlehttp started
D: Get command is: getprefs
D: Send reply for getprefs
D: STOP requested
D: Stopping client
D: Publish to topic P25A4AE30/playing : 0
D: Command client available
D: handlehttp started
D: Get command is: settings
D: Send reply for settings
D: Command client available
D: handlehttp started
D: Filename is: mp3play.html
D: Start file reply for mp3play.html
D: FileRequest received mp3play.html
D: Length of page is 2562
D: Response send
D: Command client available
D: handlehttp started
D: Get command is: mp3list
D: Send reply for mp3list
D: 11 tracks found on SD card
D: Command client available
D: handlehttp started
D: Get command is: getnetworks
D: Send reply for getnetworks
D: Command: getnetworks with parameter 0
D: Command client available
D: handlehttp started
D: Get command is: getprefs
D: Send reply for getprefs
D: Command client available
D: handlehttp started
D: Get command is: settings
D: Send reply for settings
D: Command client available
D: handlehttp started
D: HTTP input shorter than expected
D: Command client available
D: handlehttp started
D: Get command is: status
D: Send reply for status
D: Command: status with parameter 0
D: Command client available
D: handlehttp started
D: Get command is: test
D: Send reply for test
D: Command: test with parameter 0
D: Stack maintask is 4732
D: Stack playtask is 1096
D: Stack spftask  is 660
D: ADC reading is 145
D: scaniocount is 10
D: Max. mp3_loop duration is 191
D: Command client available
D: handlehttp started
D: HTTP input shorter than expected
D: Command client available
D: handlehttp started
D: Get command is: stop
D: Send reply for stop
D: Command: stop with parameter 0
D: Command client available

**Comment by Edzelf** [comment]
The debug logging looks normal.  But there are still problems with the SPI bus.
You may try to remove the lines (around line 923):
```
    //SPI Clock to 4 MHz. Now you can set high speed SPI clock.
    VS1053_SPI = SPISettings ( 5000000, MSBFIRST, SPI_MODE0 ) ;
```
The SPI will run on a slower rate.

**Comment by cherob67** [comment]
Thanks for your answer, I an going to try your solution. 
After asking my question yesterday, by chance in removing the sdcard, the sound came. I do not know why ??? and if I put the sdcard the sound is cut off immediately.
strange....

**Comment by Edzelf** [comment]
I did not realize that you had an sd card connected.  There are some known problems with some sd card interfaces.

**Comment by cherob67** [comment]
OK I have tried your solution without and with the sdcard. Without there is no difference but i think it's better to keep the code. With the sdcard, it works but the sound is bad.
Thank you
