### ISSUE TITLE
no as smooth as esp8266 ...something has gone wrong..?

### ISSUE THREAD

**Issue by SurenBono** [Edzelf/ESP32-Radio#218]
HI Ed,
Im Suren from Malaysia, recently i studied some of your work on webradio... i have done working on the D1 R1 on VS1053B and it works well....but later i managed to get a ESP32 R32 board with  another VS1053B for  testing the esp32 version.. but it is not as smooth as the esp8266.... the R32 is well compatible with the Esp32 Dev Board ....yesterday i managed to read some of the issues before seeking githubs assistance where the DEFAULTED #define NEXTION was cousing constant sys reboot..well after undefining it and choosing the #define OLED worked but it was choppy sounding... i thought mybe undefining #define TFTFILE would leech less and  but it turn out error on upload...please help

![edzelf esp32 webradio alternate module](https://user-images.githubusercontent.com/45394551/50975049-8f15f700-1527-11e9-8906-990025c2e325.gif)

**Comment by SurenBono** [comment]
Do i need to define the dummytft for the OLED display option..?

**Comment by Edzelf** [comment]
No, but if there are problems, you may switch off the display in order to find the problem.

**Comment by Edzelf** [comment]
Please show the debug output.

**Comment by SurenBono** [comment]
i tried switching the display to OLED ... also without  ...the result same...here is my debug output... i cant copy & paste the output on the serial so i took a snapshot... please check Doctor Ed..

![esp32serialdebug](https://user-images.githubusercontent.com/45394551/51000003-c952b900-1566-11e9-8010-6c0d2778cf5e.gif)

**Comment by Edzelf** [comment]
Looks like there is something wring with gpio19.  It should be high during the initial test.

**Comment by SurenBono** [comment]
.. the SPI pins...? what is the open close state..?...what should i do to fix it..?

**Comment by SurenBono** [comment]
..do i need to pullup with 3v3 manualy or ..is it a board problem/or coding error.?

**Comment by SurenBono** [comment]
...or do i need to increase the buffer size..?

**Comment by Edzelf** [comment]
Could you check the behaviour of gpio19 (miso) with a scope or a logic analyzer?  It looks like the signal is inverted.  Maybe you can use a different pin for miso.
You also might try to do a software update from the comfig page of the webinterface.  This may rule out compiling errors.

**Comment by SurenBono** [comment]
..i had similar choppy problems on esp8266 but fixed it with the v2higher bandwidth from the options...but esp32 didnt have similar options for higher bandwidth..probably in future release....regarding gpio19 ...i do not have a logic analyser..and the miso on vs1053b is directly connected to the esp32 board...sometimes it is smooth on one preset..sometimes not...and it skips selected presets automaticaly sometimes...some preset persist the same choppy playback as in esp8266..probably the way it is streamed...but still esp8266 were smoother/cheaper/easier than the esp32... after a week of observation....

**Comment by Edzelf** [comment]
In my setup the ESP32 is faster and more stable than the 8266.  Did you try one of my sugestions?

**Comment by SurenBono** [comment]
I did try flashing undefining any display...but it still lagged...When you flash into the eeprom...does it include the firmware flashing...or is the firmware separated from the sketch..


Sent from Samsung Mobile

-------- Original message --------

**Comment by Edzelf** [comment]
The firmware is in ROM.

**Comment by Edzelf** [comment]
It is impossible to erase ROM memory.  Please try thesoftware update from the config page in the webinterface.  Maybe this will give some information.  It only takes one minute....

**Comment by SurenBono** [comment]
..than why did espressif release the AT firmware and the esp32 flasher..the documentation for the adress is not there


Sent from Samsung Mobile

-------- Original message --------

**Comment by SurenBono** [comment]
Its official esp32 sucks....im discontinuing purchasing it or recommending it in the future..at least esp8266 can be installed on xp


Sent from Samsung Mobile

-------- Original message --------

**Comment by SurenBono** [comment]
..sorry edzelf on esp32 failed..its cumbersome and still failed



Sent from Samsung Mobile

-------- Original message --------

**Comment by SurenBono** [comment]
...recently i re-checked the project, i found that the freertos is not loaded up entirely before it is played...and when esp32 is playing it is not stocking on to the buffer but it played earlier than the stable esp8266 and pauses because the buffer is emptied,.refills a bit..and play ..and pause ..i doubt the 2 core is working as it should..and i never came across 32bit with 2core..the other core cant work simultaneously...regarding the gpio19.. it was high without the vs1053 connected....but i really do appreciate your programming skills...i wish i can write something like this someday ...

![freetos queue and wifi bandwith](https://user-images.githubusercontent.com/45394551/51107315-6e9cb400-1829-11e9-9cdb-24acc9696129.gif)

**Comment by SurenBono** [comment]
...I found your old more simpler version...this one lesser choppier than the current ones...the oled worked to....RINGBUFFER STILL ROCKS

![20190115_023714](https://user-images.githubusercontent.com/45394551/51133359-c5c57780-186f-11e9-8659-695a257a42ed.jpg)

**Comment by SurenBono** [comment]
![untitled](https://user-images.githubusercontent.com/45394551/51134244-f8706f80-1871-11e9-9a50-f6f56ce7d67e.gif)

**Comment by SurenBono** [comment]
.....i have solved a little of the problem for choppy play on esp32 by switching to a fiberoptic isp ......it has solved most of those usual choppy stream on copper wire on certain higher bitrate preset ...but i have not test it to run 24/7 like i did on esp8266 yet...but still i cant get the 128x32OLED to display the ip (blankscreen)..it is supposed to be a 128x64 like advertised when i purchased it...its different from the broadband ip .....only could get ip through the IDE port...i also tried to upload the patches for vs1053b from the VSLI HOMEPAGE... (vs1053b-patches260) BY #include vs1053b-patches.c ..not sure if it did what it supposed to...and modified the web interface... and the mp3 file played at last but couldnt display a proper filename yet (fat32)

![screencapture_101804879_1253772012_0](https://user-images.githubusercontent.com/45394551/51660666-7f97b300-1fe9-11e9-93e2-120f70beef1b.jpg)

**Comment by SurenBono** [comment]
...Edzelf ESP32 Webradio Sroto&Gargees Version is now tested on offgrid PWM Solar Charge Controller...it will run until 12v15a battery low power disconnects it at 11.4v as safety for battery longevity unless i get a higher Amp hour battery and higher Wattage Solar panel (car lead acid)..to make it run forever ...HiFi Amp powered by grid tied...trying to get em run both offgrid in the near future... Thanks again Edzelf for this awesome project that you gave to this world ...there was time that i was frustrated for some reason, i slept it off...  zzzzzzzzzz

![20190126_071941](https://user-images.githubusercontent.com/45394551/51779010-cbf50700-213f-11e9-9243-f030c320262b.jpg)
