### ISSUE TITLE
compiler issues

### ISSUE THREAD

**Issue by rebe0909** [Edzelf/ESP32-Radio#228]
Hi.
I tried to build my own radio with your code.
But first I need the lib for NVS (#include <nvs.h>)
Could you tell me how/and where to get it?

Thanks a lot!

**Comment by rebe0909** [comment]
Solved: I had only to switch to esp32.....

**Comment by Edzelf** [comment]
NVS is part of the ESP32 core.  Be sure you have  installed it.  There are several tutorials on this subject available on the internet.

**Comment by rebe0909** [comment]
sorry, I only forgot to switch to esp32 Board in Arduino...
