### ISSUE TITLE
use of Smartconfig for Wifi Provisioning

### ISSUE THREAD

**Issue by rmoosa** [Edzelf/ESP32-Radio#238]
Hi Ed
This is an amazing piece of code.  Well done.
This is actually a query than not an issue; but being a noob to github, i was not aware of where to communicate this query to you.
Is there any particular reason you have not chosen to utilize the ESP SmartConfig feature to the WiFi provisioning?
Thanks for the wonderful work.

**Comment by Edzelf** [comment]
No special reason.  I did not know the presence of SmartConfig when I started the project.

**Comment by rmoosa** [comment]
Thanks for the response.
