### ISSUE TITLE
Display refresh ?  Text remains and text over text seen

### ISSUE THREAD

**Issue by ilioss** [Edzelf/ESP32-Radio#24]
Hello,

After using the radio for a couple of day,s without problems I noticed a " as it looks like a refresh " problem.
On the display a line of text remains and it looks like text is displayed over a old text. See picture.
Stop and resume cleared the display and cont. with a correct text.
This phenonemom happened more frequent now.
![display-tft-esp32](https://user-images.githubusercontent.com/5527968/27947933-29892926-62f8-11e7-82ea-de84fd42b4e1.jpg)

As the display is also controled by the SPI and this looks a problem which came up after some time my idee is. Is there a relation with ths SD problem?
@Ed, I just wants to let you know this phenonemom.
If I can do something please let me know hopefully I can help.
Regards,
Theo

**Comment by Edzelf** [comment]
Try to run it without SD, i.e. remove the MISO line from the SD interface.

**Comment by ilioss** [comment]
Hallo Ed,

Thanks for your anser.
I will disconnect the miso signal from the display.
Let you know the result.
Regards,
Theo

**Comment by Edzelf** [comment]
Install the new SD library as well.

**Comment by Edzelf** [comment]
I was able to reproduce this bug.  Some stations like "NPO Radio 4" transmit very long stream titles.  I add some more space to the stream title on TFT.  The space for the station name is decreased by the same amount.

**Comment by ilioss** [comment]
Just busy to up=grade the sw.
Also the SD lib. but where can I find the new patched SD.lib??
Sorry for the inconvinience.
Theo
