### ISSUE TITLE
Another SPI/VS1053B problem - no audio output

### ISSUE THREAD

**Issue by t-c-o-d-e** [Edzelf/ESP32-Radio#246]
First of all, many thanks to the author(s), this project is badass!! I'm and will learn tons from it as I'm quite new in the ESP and micro controller world but with some history in programming.

Okay, into the problem. Already read all issues related to SPI errors on startup, none of solutions worked for me and I'm very sorry for opening another one, but I'm trying to get sound out of VS1053B for couple of days with partial luck. 

This is [ESP32 ](https://www.ebay.com/itm/Espressif-ESP32-WLAN-Dev-Kit-Board-Development-Bluetooth-Wifi-v1-WROOM32-NodeMCU/253059783728?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649) I'm having with this [VS1053B](https://www.banggood.com/VS1053-MP3-Module-Development-Board-On-Board-Recording-Function-p-1244003.html?rmmds=myorder&cur_warehouse=CN) board. To rule out things no displays or any other peripheral attached on ESP32 except VS1053B (using/uncommented dummy screen in code). Sketch compiled and uploaded to EPS32, managed to configure it through WEB, it successfully connect to local Wi Fi network, but during startup getting SPI errors while debugging trough Serial Monitor and no sound on output.

This is what I get:

> 18:42:06.268 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
18:42:06.268 -> configsip: 0, SPIWP:0xee
18:42:06.268 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
18:42:06.302 -> mode:DIO, clock div:1
18:42:06.302 -> load:0x3fff0018,len:4
18:42:06.302 -> load:0x3fff001c,len:928
18:42:06.302 -> ho 0 tail 12 room 4
18:42:06.302 -> load:0x40078000,len:8424
18:42:06.302 -> ho 0 tail 12 room 4
18:42:06.302 -> load:0x40080400,len:5868
18:42:06.302 -> entry 0x4008069c
18:42:06.642 -> 
18:42:06.642 -> D: Starting ESP32-radio running on CPU 1 at 240 MHz.  Version Wed, 24 Apr 2019 08:20:00 GMT.  Free memory 287272
18:42:06.642 -> D: Display type is DUMMYTFT
18:42:06.642 -> D: Partition nvs found, 20480 bytes
18:42:06.676 -> D: Read 46 keys from NVS
18:42:06.676 -> D: pin_ir set to 35
18:42:06.676 -> D: pin_enc_clk set to 25
18:42:06.676 -> D: pin_enc_dt set to 26
18:42:06.676 -> D: pin_enc_sw set to 27
18:42:06.676 -> D: pin_tft_cs set to 15
18:42:06.676 -> D: pin_tft_dc set to 2
18:42:06.676 -> D: pin_tft_scl set to -1
18:42:06.676 -> D: pin_tft_sda set to -1
18:42:06.676 -> D: pin_tft_bl set to -1
18:42:06.676 -> D: pin_tft_blx set to -1
18:42:06.676 -> D: pin_sd_cs set to 21
18:42:06.676 -> D: pin_vs_cs set to 5
18:42:06.676 -> D: pin_vs_dcs set to 32
18:42:06.676 -> D: pin_vs_dreq set to 4
18:42:06.709 -> D: pin_shutdown set to -1
18:42:06.709 -> D: pin_shutdownx set to -1
18:42:06.709 -> D: pin_spi_sck set to 18
18:42:06.709 -> D: pin_spi_miso set to 19
18:42:06.709 -> D: pin_spi_mosi set to 23
18:42:06.709 -> D: GPIO0 is HIGH
18:42:06.709 -> D: GPIO2 is LOW, probably no PULL-UP
18:42:06.709 -> D: GPIO4 is HIGH
18:42:06.743 -> D: GPIO5 is HIGH
18:42:06.743 -> D: GPIO12 is HIGH
18:42:06.743 -> D: GPIO13 is HIGH
18:42:06.776 -> D: GPIO14 is HIGH
18:42:06.776 -> D: GPIO15 is HIGH
18:42:06.776 -> D: GPIO16 is HIGH
18:42:06.809 -> D: GPIO17 is HIGH
18:42:06.809 -> D: GPIO18 is HIGH
18:42:06.809 -> D: GPIO19 is HIGH
18:42:06.809 -> D: GPIO21 is HIGH
18:42:06.843 -> D: GPIO22 is HIGH
18:42:06.843 -> D: GPIO23 is HIGH
18:42:06.843 -> D: GPIO25 is HIGH
18:42:06.876 -> D: GPIO26 is HIGH
18:42:06.876 -> D: GPIO27 is HIGH
18:42:06.876 -> D: GPIO32 is HIGH
18:42:06.911 -> D: GPIO33 is HIGH
18:42:06.911 -> D: GPIO34 is LOW, probably no PULL-UP
18:42:06.911 -> D: GPIO35 is LOW, probably no PULL-UP
18:42:06.911 -> D: GPIO39 is LOW, probably no PULL-UP
18:42:06.911 -> D: gpio_00 will execute uppreset = 1
18:42:06.945 -> D: gpio_12 will execute upvolume = 2
18:42:06.945 -> D: gpio_13 will execute downvolume = 2
18:42:06.945 -> D: gpio_14 will execute stop
18:42:06.945 -> D: gpio_17 will execute resume
18:42:06.945 -> D: gpio_34 will execute station = icecast.omroep.nl:80/radio1-bb-mp3
18:42:06.945 -> D: Enable pin 35 for IR
18:42:06.945 -> D: Start display
18:42:07.249 -> D: SD Card Mount Failed!
18:42:07.249 -> D: Create list with acceptable WiFi networks
18:42:07.249 -> D: Added Z to list of networks
18:42:07.249 -> D: End adding networks
18:42:07.418 -> D: Scan Networks
18:42:10.216 -> D: Scan completed
18:42:10.216 -> D: Number of available networks: 6
18:42:10.216 -> D:  1 - Z                         Signal: -72 dBm, Encryption WPA_WPA2_PSK, Acceptable
18:42:10.283 -> D: End of list
18:42:10.283 -> D: Command: clk_dst with parameter 1
18:42:10.283 -> D: Command: clk_offset with parameter 1
18:42:10.283 -> D: Command: clk_server with parameter pool.ntp.org
18:42:10.283 -> D: Command: gpio_00 with parameter uppreset = 1
18:42:10.283 -> D: Command: gpio_12 with parameter upvolume = 2
18:42:10.283 -> D: Command: gpio_13 with parameter downvolume = 2
18:42:10.283 -> D: Command: gpio_14 with parameter stop
18:42:10.283 -> D: Command: gpio_17 with parameter resume
18:42:10.283 -> D: Command: gpio_34 with parameter station = icecast.omroep.nl:80/radio1-bb-mp3
18:42:10.317 -> D: Command: ir_40bf with parameter upvolume = 2
18:42:10.317 -> D: Command: ir_c03f with parameter downvolume = 2
18:42:10.317 -> D: Command: lstmods with parameter Wed, 24 Apr 2019 07:37:27 GMT
18:42:10.317 -> D: Command: mqqprefix with parameter none
18:42:10.317 -> D: Command: mqttbroker with parameter none
18:42:10.317 -> D: Command: mqttpasswd with parameter *******
18:42:10.317 -> D: Command: mqttport with parameter 1883
18:42:10.352 -> D: Command: mqttuser with parameter none
18:42:10.352 -> D: Command: pin_enc_clk with parameter 25
18:42:10.352 -> D: Command: pin_enc_dt with parameter 26
18:42:10.352 -> D: Command: pin_enc_sw with parameter 27
18:42:10.352 -> D: Command: pin_ir with parameter 35
18:42:10.352 -> D: Command: pin_sd_cs with parameter 21
18:42:10.352 -> D: Command: pin_tft_cs with parameter 15
18:42:10.352 -> D: Command: pin_tft_dc with parameter 2
18:42:10.352 -> D: Command: pin_vs_cs with parameter 5
18:42:10.352 -> D: Command: pin_vs_dcs with parameter 32
18:42:10.386 -> D: Command: pin_vs_dreq with parameter 4
18:42:10.386 -> D: Command: preset with parameter 3
18:42:10.386 -> D: Command: preset_00 with parameter 109.206.96.34:8100
18:42:10.386 -> D: Command: preset_01 with parameter airspectrum.cdnstream1.com:8114/1648_128
18:42:10.386 -> D: Command: preset_02 with parameter us2.internet-radio.com:8050
18:42:10.386 -> D: Command: preset_03 with parameter airspectrum.cdnstream1.com:8000/1261_192
18:42:10.420 -> D: Command: preset_04 with parameter airspectrum.cdnstream1.com:8008/1604_128
18:42:10.420 -> D: Command: preset_05 with parameter us1.internet-radio.com:8105
18:42:10.420 -> D: Command: preset_06 with parameter icecast.omroep.nl:80/radio1-bb-mp3
18:42:10.420 -> D: Command: preset_07 with parameter 205.164.62.15:10032
18:42:10.420 -> D: Command: preset_08 with parameter skonto.ls.lv:8002/mp3
18:42:10.420 -> D: Command: preset_09 with parameter 94.23.66.155:8106
18:42:10.453 -> D: Command: preset_10 with parameter ihr/IHR_IEDM
18:42:10.453 -> D: Command: preset_11 with parameter ihr/IHR_TRAN
18:42:10.453 -> D: Command: toneha with parameter 0
18:42:10.453 -> D: Command: tonehf with parameter 0
18:42:10.453 -> D: Command: tonela with parameter 1
18:42:10.453 -> D: Command: tonelf with parameter 0
18:42:10.453 -> D: Command: volume with parameter 0
18:42:10.588 -> D: Slow SPI, Testing VS1053 read/write registers...
18:42:10.588 -> D: VS1053 SPI error. SB:1194 R1:1194 R2:1180
18:42:10.588 -> D: VS1053 SPI error. SB:19C8 R1:19C8 R2:19A0
18:42:10.621 -> D: VS1053 SPI error. SB:1FA4 R1:1FA4 R2:1FC0
18:42:10.621 -> D: VS1053 SPI error. SB:2B5C R1:2B5C R2:2B20
18:42:10.621 -> D: VS1053 SPI error. SB:2DB4 R1:2DC0 R2:2DB4
18:42:10.655 -> D: VS1053 SPI error. SB:3138 R1:3138 R2:3160
18:42:10.655 -> D: VS1053 SPI error. SB:35E8 R1:35E8 R2:35E0
18:42:10.690 -> D: VS1053 SPI error. SB:5B68 R1:5B60 R2:5B68
18:42:10.724 -> D: VS1053 SPI error. SB:71AC R1:71E0 R2:71AC
18:42:10.724 -> D: VS1053 SPI error. SB:80E8 R1:80E8 R2:8E00
18:42:10.758 -> D: VS1053 SPI error. SB:8A48 R1:B200 R2:8A48
18:42:10.758 -> D: VS1053 SPI error. SB:927C R1:9600 R2:927C
18:42:10.758 -> D: VS1053 SPI error. SB:9BDC R1:9BDC R2:9BA0
18:42:10.791 -> D: VS1053 SPI error. SB:9D08 R1:A200 R2:9D08
18:42:10.791 -> D: VS1053 SPI error. SB:A08C R1:A08C R2:CA00
18:42:10.791 -> D: VS1053 SPI error. SB:A668 R1:D600 R2:A668
18:42:10.825 -> D: VS1053 SPI error. SB:A794 R1:A780 R2:A794
18:42:10.825 -> D: VS1053 SPI error. SB:AB18 R1:AB18 R2:AB20
18:42:10.825 -> D: VS1053 SPI error. SB:AC44 R1:AC44 R2:E000
18:42:10.859 -> D: VS1053 SPI error. SB:AE9C R1:FA00 R2:AE9C
18:42:10.859 -> D: Connect to WiFi
18:42:10.892 -> D: Try WiFi Z
18:42:13.694 -> D: Connected to Z
18:42:13.694 -> D: IP = 192.168.1.28
18:42:16.674 -> D: Start server for commands
18:42:16.674 -> D: Network found. Starting mqtt and OTA
18:42:16.674 -> D: MDNS responder started
18:42:17.686 -> D: Rotary encoder is enabled
18:42:17.686 -> D: STOP requested
18:42:17.686 -> D: New preset/file requested (3/0) from airspectrum.cdnstream1.com:8000/1261_192
18:42:17.686 -> D: Connect to new host airspectrum.cdnstream1.com:8000/1261_192
18:42:17.720 -> D: Connect to airspectrum.cdnstream1.com on port 8000, extension /1261_192
18:42:17.821 -> D: SPI semaphore not taken within 120 ticks by CPU 0, id hspec
18:42:17.821 -> D: SPI semaphore not taken within 130 ticks by CPU 0, id hspec
18:42:17.821 -> D: SPI semaphore not taken within 140 ticks by CPU 1, id hspec
18:42:17.856 -> D: SPI semaphore not taken within 150 ticks by CPU 1, id hspec
18:42:17.856 -> D: SPI semaphore not taken within 160 ticks by CPU 0, id hspec
18:42:17.856 -> D: SPI semaphore not taken within 170 ticks by CPU 0, id hspec
18:42:17.856 -> D: SPI semaphore not taken within 180 ticks by CPU 0, id hspec
18:42:17.890 -> D: SPI semaphore not taken within 190 ticks by CPU 0, id hspec
18:42:17.890 -> D: SPI semaphore not taken within 200 ticks by CPU 0, id hspec
18:42:17.890 -> D: Connected to server
18:42:17.890 -> D: nvs_get_str failed 1102 for key basicauth, keylen is 9, len is 150!
18:42:17.923 -> D: Contents: 
18:42:17.923 -> D: SPI semaphore not taken within 210 ticks by CPU 1, id hspec
18:42:17.923 -> D: Duration mp3loop 1
18:42:17.923 -> D: SPI semaphore not taken within 220 ticks by CPU 0, id hspec
18:42:17.923 -> D: SPI semaphore not taken within 230 ticks by CPU 0, id hspec
18:42:17.923 -> D: SPI semaphore not taken within 240 ticks by CPU 0, id hspec
18:42:17.957 -> D: SPI semaphore not taken within 250 ticks by CPU 0, id hspec
18:42:17.957 -> D: SPI semaphore not taken within 260 ticks by CPU 1, id hspec
18:42:17.957 -> D: SPI semaphore not taken within 270 ticks by CPU 1, id hspec
18:42:17.957 -> D: SPI semaphore not taken within 280 ticks by CPU 0, id hspec
18:42:17.990 -> D: SPI semaphore not taken within 290 ticks by CPU 0, id hspec
18:42:17.990 -> D: SPI semaphore not taken within 300 ticks by CPU 0, id hspec
18:42:17.990 -> D: SPI semaphore not taken within 310 ticks by CPU 0, id hspec
18:42:18.024 -> D: SPI semaphore not taken within 320 ticks by CPU 0, id hspec
18:42:18.024 -> D: SPI semaphore not taken within 330 ticks by CPU 0, id hspec
18:42:18.024 -> D: SPI semaphore not taken within 340 ticks by CPU 0, id hspec
18:42:18.057 -> D: SPI semaphore not taken within 350 ticks by CPU 1, id hspec
18:42:18.057 -> D: SPI semaphore not taken within 360 ticks by CPU 1, id hspec
18:42:18.057 -> D: SPI semaphore not taken within 370 ticks by CPU 0, id hspec
18:42:18.057 -> D: SPI semaphore not taken within 380 ticks by CPU 0, id hspec
18:42:18.091 -> D: SPI semaphore not taken within 390 ticks by CPU 0, id hspec
18:42:18.091 -> D: SPI semaphore not taken within 400 ticks by CPU 0, id hspec
18:42:18.091 -> D: SPI semaphore not taken within 410 ticks by CPU 0, id hspec
18:42:18.124 -> D: SPI semaphore not taken within 420 ticks by CPU 0, id hspec
18:42:18.124 -> D: SPI semaphore not taken within 430 ticks by CPU 0, id hspec
18:42:18.124 -> D: SPI semaphore not taken within 440 ticks by CPU 0, id hspec
18:42:18.159 -> D: SPI semaphore not taken within 450 ticks by CPU 1, id hspec
18:42:18.159 -> D: SPI semaphore not taken within 460 ticks by CPU 1, id hspec
18:42:18.159 -> D: SPI semaphore not taken within 470 ticks by CPU 0, id hspec
18:42:18.159 -> D: SPI semaphore not taken within 480 ticks by CPU 0, id hspec
18:42:18.192 -> D: SPI semaphore not taken within 490 ticks by CPU 0, id hspec
18:42:18.192 -> D: SPI semaphore not taken within 500 ticks by CPU 0, id hspec
18:42:18.192 -> D: SPI semaphore not taken within 510 ticks by CPU 0, id hspec
18:42:18.226 -> D: SPI semaphore not taken within 520 ticks by CPU 0, id hspec
18:42:18.226 -> D: SPI semaphore not taken within 530 ticks by CPU 0, id hspec
18:42:18.226 -> D: SPI semaphore not taken within 540 ticks by CPU 0, id hspec
18:42:18.226 -> D: SPI semaphore not taken within 550 ticks by CPU 0, id hspec
18:42:18.259 -> D: SPI semaphore not taken within 560 ticks by CPU 1, id hspec
18:42:18.259 -> D: SPI semaphore not taken within 570 ticks by CPU 1, id hspec
18:42:18.259 -> D: SPI semaphore not taken within 580 ticks by CPU 0, id hspec
18:42:18.292 -> D: SPI semaphore not taken within 590 ticks by CPU 0, id hspec
18:42:18.292 -> D: SPI semaphore not taken within 600 ticks by CPU 0, id hspec
18:42:18.292 -> D: SPI semaphore not taken within 610 ticks by CPU 0, id hspec
18:42:18.326 -> D: Switch to HEADER
18:42:18.326 -> D: Headerline: Content-Type: audio/mpeg
18:42:18.326 -> D: audio/mpeg seen.
18:42:18.326 -> D: Headerline: icy-br:192
18:42:18.326 -> D: SPI semaphore not taken wo: ice-samplerate=44100;ice-bitrat
18:42:18.326 -> D: Headerline: ice-audio-info: ice-samplerate=44100;ice-bitrate=192;ice-channels=2
18:42:18.326 -> D: Headerline: icy-b takeD: SPI semaphore not taken within 630 ticks by CPU 0, id hspec
18:42:18.326 -> 
18:42:18.326 -> D: Headerline: icy-description:Magic Oldies Florida HD 192 Kbps with the Best Oldies on the Planet!
18:42:18.359 -> D: Headerlinhore not taken within 640 ticks bD: SPI semaphore not taken within 640 ticks by CPU 0, id hspec
18:42:18.359 -> 
18:42:18.359 -> D: Headerline: icy-name:Magic Oldies Florida
18:42:18.359 -> D: Headerline: icy-private:0
18:42:18.359 -> D: Headerline: icy-pub:1
18:42:18.359 -> D: Hea semaphore not taken within 650 ticks by CPU 0, id
18:42:18.359 -> D: SPI semape: Server: Icecast 

Checked wiring couple of times, using default values for CS(5), DCS(32) and DREQ(4). Having external 5V power supply for VS1053B, ground is tightly connected with ESP32. 

Without touching a single wire, so absolutely no change in wiring/pinout I can compile this example sketch from VS1503 library and it plays, getting sound on output.

> #include <VS1053.h>  //https://github.com/baldram/ESP_VS1053_Library
> #include <WiFi.h>
> #include <HTTPClient.h>
> #include <esp_wifi.h>
> #include <SPI.h>
> 
> #define VS1053_CS   5 
> #define VS1053_DCS   32  
> #define VS1053_DREQ  4 
> 
> #define VOLUME  90 // volume level 0-100
> 
> int radioStation = 0;
> int previousRadioStation = -1;
> const int previousButton = 12;
> const int nextButton = 13;
> 
> char ssid[] = "Z";            //  your network SSID (name) 
> char pass[] = "xxxxxxxxx";   // your network password
> 
> // Few Radio Stations
> char *host[6] = {"50.7.77.114","50.7.70.58","149.255.59.162","radiostreaming.ert.gr","realfm.live24.gr", "secure1.live24.gr"};
> char *path[6] = {"/","/","/1","/ert-kosmos","/realfm","/skai1003"};
> int   port[6] = {8495,8672,8062,80,80,80};
> 
> int status = WL_IDLE_STATUS;
> WiFiClient  client;
> uint8_t mp3buff[32];   // vs1053 likes 32 bytes at a time
> 
> VS1053 player(VS1053_CS, VS1053_DCS, VS1053_DREQ);
> 
> void IRAM_ATTR previousButtonInterrupt() {
> 
>   static unsigned long last_interrupt_time = 0;
>   unsigned long interrupt_time = millis();
>  
>  if (interrupt_time - last_interrupt_time > 200) 
>  {
>    if(radioStation>0)
>     radioStation--;
>     else
>     radioStation = 3;
>  }
>  last_interrupt_time = interrupt_time;
> }
> 
> void IRAM_ATTR nextButtonInterrupt() {
> 
>   static unsigned long last_interrupt_time = 0;
>   unsigned long interrupt_time = millis();
>  
>  if (interrupt_time - last_interrupt_time > 200) 
>  {
>    if(radioStation<4)
>     radioStation++;
>     else
>     radioStation = 0;
>  }
>  last_interrupt_time = interrupt_time;
> }
> 
> void setup () {
>  
>    Serial.begin(9600);
>    SPI.begin();
>      
>    pinMode(previousButton, INPUT_PULLUP);
>    pinMode(nextButton, INPUT_PULLUP);
> 
>    attachInterrupt(digitalPinToInterrupt(previousButton), previousButtonInterrupt, FALLING);
>    attachInterrupt(digitalPinToInterrupt(nextButton), nextButtonInterrupt, FALLING);
> 
>    initMP3Decoder();
>    connectToWIFI();
> 
> }
> 
> void loop() {
>      
>       if(radioStation!=previousRadioStation)
>       {
>            station_connect(radioStation);
>            previousRadioStation = radioStation; 
>       }
>       
>       if (client.available() > 0)
>       {
>         uint8_t bytesread = client.read(mp3buff, 32);
>         player.playChunk(mp3buff, bytesread);
>       }
> }    
>   
> void station_connect (int station_no ) {
>     if (client.connect(host[station_no],port[station_no]) ) Serial.println("Connected now"); 
>     client.print(String("GET ") + path[station_no] + " HTTP/1.1\r\n" +
>                "Host: " + host[station_no] + "\r\n" + 
>                "Connection: close\r\n\r\n");                
>   }
> 
>   void connectToWIFI()
>   {
>     WiFi.begin(ssid, pass);
>       while (WiFi.status() != WL_CONNECTED) {
>         delay(500);
>         Serial.print(".");
>    }
>    Serial.println("WiFi connected");
>    delay(1500);
>   }
> 
>   void initMP3Decoder()
>   {
>     player.begin();
>     player.switchToMp3Mode(); // optional, some boards require this
>     player.setVolume(VOLUME);
>     delay(3000);
>   }

And that's where I'm all lost. What else can I check? Thanks in advance and keep up good work!

**Comment by Edzelf** [comment]
There is something wrong with the SPI bus.  Maybe you have a logic analyzer.  The cheap chinese ones understand the SPI protocol.

**Comment by t-c-o-d-e** [comment]
Thanks for a quick reply!

Unfortunately I don't have. But how it works with simple code from VS1053 library example, if it is any trouble with SPI or hardware related?

**Comment by t-c-o-d-e** [comment]
Also tried with ESP32 Node MCU 32S, it won't work with neither code :/. So strange.. faulty VS1053 board maybe?
Should get two new VS1053 boards tomorrow and try again. This is so frustrating :(.

**Comment by Rainer-G** [comment]
Hi,

I had a look at you log and the sample code you attached.
The difference I can see that your code uses SPI.begin() with no parameters, whereas ESP32Radio uses :

  SPI.begin ( ini_block.spi_sck_pin,                     // Init VSPI bus with default or modified pins
                     ini_block.spi_miso_pin,
                     ini_block.spi_mosi_pin ) ;

Running SPI.begin without parameters uses the default setting from the board file, the ESP32Radio software may override thes values. E.g. on my Adafruit Feather I’m using
D: Command: pin_spi_miso with parameter 19
D: Command: pin_spi_mosi with parameter 18
D: Command: pin_spi_sck with parameter 5

Can you check which pins of the ESP32 the VS1053 SPI pins are connected ? 
You can find the default pins in the board file or do a print with the SPI names MISO, MOSI, SCLK 
    like   Serial.println( MOSI ); etc

Best regards, Rainer



Gesendet von Mail für Windows 10

Von: t-c-o-d-e
Gesendet: Sonntag, 28. April 2019 22:03
An: Edzelf/ESP32-Radio
Cc: Subscribed
Betreff: Re: [Edzelf/ESP32-Radio] Another SPI/VS1053B problem - no audiooutput (#246)

Also tried with ESP32 Node MCU 32S, it won't work with neither code :/. So strange.. faulty VS1053 board maybe?
Should get two new VS1053 boards tomorrow and try again. This is so frustrating :(.

**Comment by t-c-o-d-e** [comment]
Thank you for your insight!

Checked, serial print says: MOSI 23, MISO 19, SCK 18, 

Well, tried one more time with sample code, it plays but looks like it loses some packets/data, I'm more and more towards defective VS1053B board. Will have two new boards tonight and try.

**Comment by t-c-o-d-e** [comment]
@Edzelf I've tried with two new VS1053B boards, with same result. Can you or anybody else confirm that your code works with [this ](https://www.ebay.co.uk/itm/VS1053-MP3-Module-Development-Board-w-On-Board-Recording-Function-SPI-Interface/310645105092?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D56924%26meid%3D43a3252da51f4dda858264ba89413672%26pid%3D100675%26rk%3D3%26rkt%3D15%26mehot%3Dpp%26sd%3D323789676275%26itm%3D310645105092&_trksid=p2481888.c100675.m4236&_trkparms=pageci%3Abb02c111-6ab7-11e9-8e21-74dbd1803149%7Cparentrq%3A6aa407f516a0ac3c3bc902aafff03d25%7Ciid%3A1) VS1053 board? What I'm doing wrong :(((?

**Comment by sarahjaneuk** [comment]
The green (LC Technology) VS1053 board in your link looks identical to the one I am using and I can confirm it works fine in my set up.
Hope you get yours working.

**Comment by t-c-o-d-e** [comment]
@sarahjaneuk thank you!

FOUND IT!!!!  Jumper wires (15 cm) were too long! Using 5 cm ones and I get occasionally one SPI error on startup, but most of the times it went through without errors and I finally having sound on output.

But, now having totally different issue, volume going down automatically for no reason!?

**Comment by t-c-o-d-e** [comment]
Figured that one too, rotary encoder should be connected or disabled in config if not connected. Otherwise volume is going down to 0 every time.

**Comment by sarahjaneuk** [comment]
Excellent. The IR route is probably a better option. I found the rotary encoder a bit too fiddly.

In case you haven't seen it, check out Andreas Speiss's video on this project: https://www.youtube.com/watch?v=hz65vfvbXMs

Enjoy your new radio.

**Comment by gregoryperrin** [comment]
Thanks to your comment https://github.com/Edzelf/ESP32-Radio/issues/246#issuecomment-487953465 i found the answer to my problem (volume going down automatically)
