### ISSUE TITLE
Permanent reboot

### ISSUE THREAD

**Issue by Milka-Cow** [Edzelf/ESP32-Radio#247]
Hi,
my radio works fine since 2 month or so now.
It will start and reboot permanetly.
My son programmed the ESP in the past. He said he could not find any problems.
Also the different SSD are seen if he connect it to his PC.

Starting...
Version January 05 19
Connect to Wifi
Then 192.168.4.1
Starting...

Any idea what I can do?

**Comment by Edzelf** [comment]
Reboot is often caused by weak powersupply.
Please try to run the radio with a different powersupply.

**Comment by Milka-Cow** [comment]
Hi
before I had a 1A psu, same problem with a quality 2A psu.
Both show 5V with voltmeter, also wiring on pcb is tick enough.

**Comment by emiklen** [comment]
i had the same problem, and in my case the cause was the preset station, may be some offending icy metadata, changed preset to another station  and the reboot stopped.

**Comment by Milka-Cow** [comment]
@emiklen: The solution do not helped.
My son had time now and he re programmed the chip. Then it worked fine.
So no idea what happend.
