### ISSUE TITLE
[ASK] Make Startup playing mp3 random not radio station

### ISSUE THREAD

**Issue by Hesoyam666** [Edzelf/ESP32-Radio#248]
Hi..
i have little problem to make boot first to playing mp3 files random.. i have try change value define "localfile = true" or call function in last line void setup() "analyzeCmd("mp3track = 0");" not success..  
can anyone help me ? thanks :confused:

**Comment by Edzelf** [comment]
Put "mp3track=0" in your preferences.  Remove "preset=<n>".

**Comment by Hesoyam666** [comment]
wow work like a charm :dancer:  thanks you
