### ISSUE TITLE
playback stopps when switching from Control to Config

### ISSUE THREAD

**Issue by erichegit** [Edzelf/ESP32-Radio#268]
I only want to make sure, if only I face this issue.
When I open the Webinterface and play a station everything works fine, also when closing the Browser.

BUT when clicking the CONFIG Menu the stream stopps :-1: 
Doesn`t matter which station - so I can reproduce this behaviour.

**Comment by Edzelf** [comment]
Filling the config page is a time consuming operation.  Therefore the radio is stopped.
