### ISSUE TITLE
volume goes down to zero automatically

### ISSUE THREAD

**Issue by TCakshay** [Edzelf/ESP32-Radio#281]
i have tried the setup without connecting a display .it works fine ,but volume goes down to zero with no reason

**Comment by Edzelf** [comment]
If the program turns the volume down, you should see the reason in the logging on the serial port.

**Comment by TCakshay** [comment]
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Publish to topic PF9BF713C/volume : 51
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Publish to topic PF9BF713C/volume : 34
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Publish to topic PF9BF713C/volume : 13
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1
D: Rotation count -1

**Comment by TCakshay** [comment]
this is the serial output that i get while its streaming

**Comment by Edzelf** [comment]
Notice that that the program sees left rotation of the rotary encoder, which is interpreted as "lower the volume".  Find out what pins are used for the encoder.  It is probably not configurated....

**Comment by TCakshay** [comment]
yeah, i have got it. thank you
