### ISSUE TITLE
This is not a VS1053, but a VS1003 instead!

### ISSUE THREAD

**Issue by AloisKlingler** [Edzelf/ESP32-Radio#296]
hello!

I recognized the following messages:

D: Slow SPI, Testing VS1053 read/write registers...
D: This is not a VS1053, but a VS1003 instead!
D: Fast SPI, Testing VS1053 read/write registers again...
D: This is not a VS1053, but a VS1003 instead!
D: endFillByte is 0

I found out, it's only necessary to return "okay = true" on line 904 and the VS1053 module worked.

As I also had the effect of touching the breadboard-cables make stuttering sound I soldered everything. Now the stuttering sound is away, but the message is still there. :-)

So I recompiled with okay=false again, with the effect, no sound at all. Still with okay = true it works flawless.

It looks like I got a module with a wrong chip, did I?
Are there any documented differences or disadvantages between VS1053 and VS1003? The module looks exactly the same. On the chip I can read a VS1003B.

Thank you! :-)

Best regards
Alois

**Comment by Edzelf** [comment]
Yes, you got the wrong chip.  If it works for you: no problem.
But the software is written for the VS1053.

**Comment by AloisKlingler** [comment]
thanks. :-)
