### ISSUE TITLE
DRAM size issue?

### ISSUE THREAD

**Issue by giddyhup** [Edzelf/ESP32-Radio#345]
I'm trying to compile the sketch for a WEMOS LOLIN32 WROOM board and and get this error: ``DRAM segment data does not fit. [...] region `dram0_0_seg' overflowed by 13800 bytes``. I tried other board settings and memory setting but can't find one that works. What am I missing?

**Comment by Edzelf** [comment]
Try to compile for "ESP32 DEV Module".  PSRAM disabled.

**Comment by giddyhup** [comment]
Thanks for the lightning fast response. I did that and also set PubSub's max packet size to its default 512 (for a different project it had been increased). Now it seems to compile.
