### ISSUE TITLE
vs1003 is too hot

### ISSUE THREAD

**Issue by clear-sky** [Edzelf/ESP32-Radio#386]
hi all
i have a fake vs1053 board that has vs1003 chip
i read all comments and could use it (commented line 921 as below)
//    okay = false ;
i can hear mp3 stations but chip vs1003 is too hot and i can not remain my finger on it more than 10 seconds

is that my problem or this is normal?

![HTB1n3KiOVXXXXcXXpXXq6xXFXXXp](https://user-images.githubusercontent.com/6883905/95384860-127d9b80-08fa-11eb-82a4-a45c70f63d1b.jpg)

**Comment by clear-sky** [comment]
to dear vs1053 owners
do you have this problem?

**Comment by Edzelf** [comment]
Mine (VS1053) is 22.1 degrees Centigrade.

**Comment by clear-sky** [comment]
thanks dear ed 
you are very kind

**Comment by clear-sky** [comment]
hi all
found the problem
i had connected earphone output to pam8403 amplifier
in fact i had connected earphone  ground to system ground 
earphone ground is not normal ground and should not be connect to system ground 
if you make this mistake high current passes through vs1003 and cause chip overheat !
just disconnected ground between vs1003 module and pam 8403 !
now my vs1003 is cold !

**Comment by Edzelf** [comment]
Yes, you have to use some kind of isolation like double powersupplies or transformers.
