### ISSUE TITLE
some ideas!

### ISSUE THREAD

**Issue by clear-sky** [Edzelf/ESP32-Radio#414]
hi dear ed! 
i have some suggestions or ideas for your great work
you may dont like some of my ideas thus first of all please forgive me!
1-add rtc
would like this radio to be a desk clock with radio but there is a problem with this idea: when only clock is running there is no need to internet but this radio does not boot without internet!
if you dont like this idea can you give me some advise to do that?

2-add search option!
it looks funny at first but is true
i am linux user and in kde there is a radio widget that has search option! and works great
https://store.kde.org/p/1313987
i am not sure if windows users have this options in their desktop?

3-add album art
in that widget i said before when a music playes it connects to another site(last.fm) and take music cover and shows it!
if you add this option i am sure this radio will be  a jewel!

thanks for your notice!

**Comment by donnersm** [comment]
I am implementing both as we speak... cover art and  search ...based on another project
schreibfaul1/ESP32-MiniWebRadio
