### ISSUE TITLE
Not realy an issue, but I would need help

### ISSUE THREAD

**Issue by Kristian-12345** [Edzelf/ESP32-Radio#416]
Hello, I try to connect push buttons to shift the programmed stations up and down instead of the rotary encoder. 
But I am not sure how to do that. I found many lines in the code which deal with push buttons, but I am not sure where I can define and set them up.
Maybe somebody has done this before an could help me?

Thanks

Kristian

**Comment by Edzelf** [comment]
You can add pushbuttons to every free input pin.  The document describes how to define a function to a push button pin.

**Comment by Kristian-12345** [comment]
Thanks and sorry for that question
