### ISSUE TITLE
library list

### ISSUE THREAD

**Issue by donnersm** [Edzelf/ESP32-Radio#422]
having a hard time getting the right libraries
IS there a list available of used libraries.
Which one are build in ?
Which one to install and most important the version!
Maybe someone can provide a link to the libraries needed
Thanks

**Comment by Edzelf** [comment]
See page 23 of the document.

**Comment by donnersm** [comment]
O you are right! missed it! ( As usual...most programming errors are between the seat and the keyboard.. ;-)
