### ISSUE TITLE
vs1053 with mic

### ISSUE THREAD

**Issue by pipikupi** [Edzelf/ESP32-Radio#444]
I have vs1953 board with mic and have no audio but only sound from mic will that mic needs to be treated different way?

**Comment by Edzelf** [comment]
The VS1053 board, as described in the documentation also has a microphone.  It is not used.

**Comment by pipikupi** [comment]
Last night I find the reason of the problem vs1053 chip is not soldered properly when I pressed it to board started working so have to fix that. Thanks for fast response
