### ISSUE TITLE
Previous station name retained when current name is absent

### ISSUE THREAD

**Issue by dheydeck** [Edzelf/ESP32-Radio#445]
First, my compliments on this excellent project.
When listening to the following radio stations:
preset_00 = 79.120.77.11:8000/deltablues             #  0 - Radio Caprice: Delta Blues
preset_01 = 79.111.119.111:8000/contclass            #  1 - Radio Caprice: Contemporary Classics
The name of the station appears to be absent. If one of these is the first station to be listened to,  just a hyphen followed by the track name is displayed:
 "- Stockhausen - Gruss"
If a different station has been played previously, its name is prepended to the track name:
"Blue Skies Radio - Stockhausen - Gruss"
![image](https://user-images.githubusercontent.com/62849409/109010463-b4363700-76a7-11eb-9553-835e262c090f.png)
I have just recompiled with the 19-feb-2021 commit and the issue persists.

**Comment by utw3v0** [comment]
i could imagine it has to do with those colons but i'm not sure so maybe you just try it ?

**Comment by dheydeck** [comment]
Thanks, utw3v0- I really appreciate the thought. In fact the colons were originally hyphens,  and I changed them to colons because I thought the hyphens might be the problem. The issue is the same in both cases! Here's an example of it working with colons:
![image](https://user-images.githubusercontent.com/62849409/109017396-09c21200-76af-11eb-8b90-a39c349f3d7d.png)

**Comment by dheydeck** [comment]
I have submitted Pull Request #450, my first attempt so I may not have followed the correct process. The code nulls the icyname String prior to dbgprint ( "Switch to HEADER" ) ; and also caters for the case where icyname has not been populated and suppresses the hyphen that is usually present between icyname and the the stream title icystreamtitle.
Any suggestions/corrections relating to my use of GitHub are appreciated.
