### ISSUE TITLE
Can not play Opus format

### ISSUE THREAD

**Issue by thanhnc-iot** [Edzelf/ESP32-Radio#446]
Hello all,
I'm using IceCast server and creat mount a point.
Source client: BUTT
Audio format: OPUS/128k
My board can not play while I can play by web browser (Google chrome).
Please show me the way to solve this. (I need to use this board for monitoring few channel with OPUS format).
Tks.

**Comment by NonaSuomy** [comment]
Opus is not currently supported by the VS1053 that this project is using. OGG =/= Opus

You would have to start with www.vlsi.fi first to get it supported by the VS1053.

http://www.vsdsp-forum.com/phpbb/viewtopic.php?t=1026
