### ISSUE TITLE
shutdown not working

### ISSUE THREAD

**Issue by MHz000** [Edzelf/ESP32-Radio#448]
Hi Ed
declared in Config  pin_shutdown = 34                                  
Save & Restart, source new compiled and flashed 
neithher set Vol = 0, Mute nor Stop resets pin 34 to GND
wiring is ok
What is missing, what wents wrong?
Thank-you

**Comment by NonaSuomy** [comment]
GPIO 34-39 have no internal configurable pullup/down, you have to add a 10kohm resistor from the GPIO to 3.3V.

**Comment by MHz000** [comment]
Ok, I'll check.
In the source code? In one of the header files? Pls advice.
Thank you

Am Mo., 1. März 2021 um 15:44 Uhr schrieb Ed Smallenburg <
notifications@github.com>:

**Comment by MHz000** [comment]
Nona,
as output port there is no need for a pull up R
Thank-you

**Comment by NonaSuomy** [comment]
34-39 are input only.

**Comment by MHz000** [comment]
in main.cpp line 946:
pinMode(shutdown_pin, OUTPUT);

in Config page WEB interface
pin_shutdown = 34

something missing, wrong interpreted?

Am Mo., 1. März 2021 um 16:48 Uhr schrieb NonaSuomy <
notifications@github.com>:

**Comment by MHz000** [comment]
Nona thank-you for the hint, I'm not aware of that HW limitation. *)
Try to find an other - useable - pin. Maybe Edzelf will give some advice how to use the shutdown function of ESP32-Radio.

*) my ESP32 pin map GPIO34/35  is yellow colored. Are output GPIOs blue colored?

**Comment by NonaSuomy** [comment]
https://drive.google.com/file/d/1gbKM7DA7PI7s1-ne_VomcjOrb0bE2TPZ/view

**Comment by MHz000** [comment]
using pin 7 GPIO17 => U2_TXD as shutdown works fine now!
Set: pin_shutdown = 17   in Web Config page
Thank-you Nona for pointing me to special HW caracteristics
