### ISSUE TITLE
help for adding TFT_eSPI

### ISSUE THREAD

**Issue by clear-sky** [Edzelf/ESP32-Radio#453]
hi all
i am very happy with this great work
very very thanks especially for adding search tool for this great project
i am trying to add ili9488 spi 480x320
the only working driver that i found is here
https://github.com/Bodmer/TFT_eSPI
can anybody give me some help for using this display for this project
my problem is here
tft = new Adafruit_ILI9341 ( ini_block.tft_cs_pin,ini_block.tft_dc_pin ) ; (this is part of esp32radio code)
if you see driver code will know all pins of display is configured in driver folder (User_Setup_Select.h) 
i could not find any way to config display pin  in sketch

by the way ch376 lib is updated

**Comment by silk-indus** [comment]
Dear clear-sky.
Look on my fork, I did it.

**Comment by clear-sky** [comment]
thanks for reply
