### ISSUE TITLE
Arduino IDE

### ISSUE THREAD

**Issue by mousemat86** [Edzelf/ESP32-Radio#473]
I'm attempting to load and build this using Arduino IDE however opening ESP32-Radio.ino from the directory ESP32-Radio I am presented with only the wrapper file – see screen grab. I would expect the other files from src to open alongside the sketch... 

What am I doing wrong? Arduino IDE 1.8.15 

<img width="1319" alt="Screenshot 2021-07-27 at 21 52 07" src="https://user-images.githubusercontent.com/57290277/127225670-27aab34f-78c4-4b93-8f8d-7ef5d4776d51.png">

**Comment by Edzelf** [comment]
The IDE will compile and link all sources that are in the directory where the .ino file lives in.

**Comment by mousemat86** [comment]
OK thanks, got it
