### ISSUE TITLE
Hanging on starting

### ISSUE THREAD

**Issue by ilioSS53** [Edzelf/ESP32-Radio#483]
Hi Ed,
At the moment I started to build a new radio with the naked ninja pcb.
Programming with performio succeded. Lots of errors but the code is uploaded. 
The startup is stopped at starting...
Only the display is connected.
Do I need to remove the not used rotary encoder, sdcard etc.lines?
It is not possible to reach the page 192.168.4.1 or ESP32Radio?
Also my old ssid was loaded?? This is an old problem which can be solved by entrring the new ssid via the webpage correct?
Like to hear.
Kind regards
ilioSS

**Comment by ilioSS53** [comment]
Hi Ed,

The latest esp32 radio with search function is a  piece from a next level. Realy amazing. With a smile all kind of music at hand. I enjoy it.
Regards ilioSS

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

**Comment by ilioSS53** [comment]
Hello Ed,
After one night printing here my new ESP32 radio.
Greetz ilioSS

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

**Comment by Edzelf** [comment]
Where?
And please remove Outlook advertisement.

**Comment by ilioSS53** [comment]
Hi Ed,
Sorry ads. Switched off.
Photo didnot come with the e-mail?
Here it is.
![20211102_134629](https://user-images.githubusercontent.com/92124659/139856769-d492de05-a782-4af4-800f-b0680f7aa753.jpg)
![IMG-20211102-WA0002](https://user-images.githubusercontent.com/92124659/139856813-f7b06202-de33-418b-ab77-f93c0c8adb63.jpeg)
Regards ilioSS

**Comment by ilioSS53** [comment]
Hi Ed,

I,am a bit confused.
The "old" version appeared to have lost his SD card function?
During start-up SD card not displayed.
In the menu it is mentioned?

Already some test done no sigh of recognition of the SD card.

Is the SD card no longer in the system?

Like to hear ilioSS

Note: the new radio 3D printed last for just a couple of weeks. For a better sound I filled the casing with demping material. After al a bad ideer. The ESP32 is burn-out.
