### ISSUE TITLE
Fix for weekdays in LCD2004.h

### ISSUE THREAD

**Issue by h1aji** [Edzelf/ESP32-Radio#487]
I noticed that Sunday is always shown as ??? Little bit googling said that **timeinfo.tm_wday** 0 is for sunday, 
So this line 
https://github.com/Edzelf/ESP32-Radio/blob/bc25a066e79704afec52f056960ca8b89bbf54f4/src/LCD2004.h#L471

Should be modified to 
`  const char* WDAYS [] = { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" } ;
`

**Comment by Edzelf** [comment]
Fixed
