### ISSUE TITLE
LCD1602 Is it correct?

### ISSUE THREAD

**Issue by zkarolyi** [Edzelf/ESP32-Radio#488]
Hi Edzelf,

I like the Radio, thank you!!! It is working now.

But ckecking the code I found this in main.cpp:
#ifdef LCD1602I2C
#include "**oled.h.h**" // For LCD 1602 display (I2C)
#endif

I think it should be like:
#ifdef LCD1602I2C
#include "**LCD1602.h**" // For LCD 1602 display (I2C)
#endif
 
Not? Why?

**Comment by Edzelf** [comment]
You are right.  Fixed.  It was already fixed in version 2 of the radio.

**Comment by zkarolyi** [comment]
Thank you!
