### ISSUE TITLE
mp3play_html.h

### ISSUE THREAD

**Issue by koskee** [Edzelf/ESP32-Radio#7]
Having trouble compiling.. It appears you added an include to a file called mp3play_html.h (presumably a new page for the web interface) 2 days ago, and loosely implemented it into the sketch, but I can't find it anywhere. Did you forget to upload it maybe? Or am I just blind? lol

**Comment by Edzelf** [comment]
Fixed.

**Comment by koskee** [comment]
Thanks :)
