### ISSUE TITLE
STOP, RESUME in 1 pin

### ISSUE THREAD

**Issue by udavst** [Edzelf/ESP32-Radio#71]
Is it possible to make play / stop with one button?

**Comment by Edzelf** [comment]
Implemented this in 02-jan-2018 version.

**Comment by udavst** [comment]
Thanks!

**Comment by udavst** [comment]
This is inconvenient (1 point), now the radio is turned on at all without a preset, and after switching on from the IR does not play anything, there are still stations to switch.
I want to be in the STOP mode when starting the radio.
