### ISSUE TITLE
how to do it Power on - not autoplay

### ISSUE THREAD

**Issue by udavst** [Edzelf/ESP32-Radio#72]
Tell me how to make sure that the radio does not turn on itself, when power is applied?

**Comment by Edzelf** [comment]
Solution 1:
Just add the line:
currentpreset = ini_block.newpreset ;
just before the end of the setup() function.

Solution 2:
remove lines 3049, 3050 and 3052 ( 2 januari 2018 version ).

**Comment by udavst** [comment]
This is inconvenient (1 point), now the radio is turned on at all without a preset, and after switching on from the IR does not play anything, there are still stations to switch.
I want to be in the STOP mode when starting the radio.
