### ISSUE TITLE
Does not enter AP mode after erasing Flash

### ISSUE THREAD

**Issue by bbx10** [Edzelf/ESP32-Radio#8]
Erase flash (IDF make erase_flash) then upload ESP32-radio firmware. ESP32-radio does not enter local AP mode. The following fixes the issue.

```C
@@ -1547,10 +1547,14 @@ bool connectwifi()
     if (  WiFi.waitForConnectResult() != WL_CONNECTED ) // Try to connect
     {
       localAP = true ;                                  // Error, setup own AP
     }
   }
+  else
+  {
+      localAP = true ;                              // no ssid/pw so setup local AP
+  }
   if ( localAP )                                        // Must setup local AP?
   {
     dbgprint ( "WiFi Failed!  Trying to setup AP with name %s and password %s.", NAME, NAME ) ;
     WiFi.softAP ( NAME, NAME ) ;                        // This ESP will be an AP
     delay ( 5000 ) ;
@@ -3572,6 +3576,6 @@ String httpheader ( String contentstype )
```

**Comment by Edzelf** [comment]
I will include this code in the next realease.

**Comment by lonelyjack** [comment]
Where can i paste this part to the code?

**Comment by bbx10** [comment]
The file is Esp_radio.ino. The function name is connectwifi(). The line number is 1547 or thereabouts.

**Comment by lonelyjack** [comment]
bbx10
Could you, please, make .ino and share it

**Comment by bbx10** [comment]
Rename this to Esp32_radio.ino. github does not allow file names ending in ino.

[Esp32_radio.txt](https://github.com/Edzelf/ESP32-Radio/files/1100615/Esp32_radio.txt)

**Comment by Edzelf** [comment]
Fixed.

**Comment by lonelyjack** [comment]
Thank you, guys)))
